---
title: "5.9.1. Enable advanced options in modules"
other-links:
  - text: "Version française"
    href: ../fr/5-9-1-activer-les-options-avancees-dans-les-modules.qmd
    icon: translate
---

Checking the "Enable advanced options in modules" box in the Settings module will result in additional options to be accessible to the user across different modules of AccessMod, as shown in the information reported in the following table:

+----------------------+-------------------+--------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Module/tool**      | **Section**       | **Advanced option**                                                      | **Description**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+----------------------+-------------------+--------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Data                 | Filter            | Show internal data check button                                          | Checking this button will make several types of internal data sets visible to the users (e.g., "friction", "speed", and "landcover merged bridge" raster data sets) in the "Available Data" table. See below for an explanation of these data sets.                                                                                                                                                                                                                                                                          |
+----------------------+-------------------+--------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Toolbox\             | Roads tab         | Show checkbox to "Do not add 1000 to class \< 1000"                      | If this button is checked, the values of the road categories (if \<1000) will be kept as they are defined in the road layer (and 1000 will not be added to these categories)                                                                                                                                                                                                                                                                                                                                                 |
| Merge land cover     |                   |                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+----------------------+-------------------+--------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Accessibility\       | Analysis settings | Optimize dynamically computation according to the scenario               | [Using this option can drastically decrease the computation time, particularly when the number of cells is large, that is when the extent of the zone is large and at high resolution. The optimisation procedure clips all raster around each facility, with clip surfaces corresponding to the maximum surface of a catchment that would be computed by using the largest speed found in the travel scenario and applied everywhere. It is recommended to use this option with the geographic coverage analysis.]{.c-blue} |
| Geographic coverage\ |                   |                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Referral\            |                   |                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Scaling up           |                   |                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+----------------------+-------------------+--------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Accessibility\       | Analysis settings | Save analysis parameters without computing                               | This option is used to prepare the analysis and its configuration file which is then saved, but the analysis is not executed. The configuration file can then be used with the [Replay](appendix-8-replay-functionality.qmd) mode.                                                                                                                                                                                                                                                                                           |
| Geographic coverage\ |                   |                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Referral\            |                   |                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Scaling up           |                   |                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+----------------------+-------------------+--------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Accessibility\       | Analysis settings | Use 'floor' rounding when converting travel time from seconds to minutes | Historically, AccessMod uses a *floor* function to convert travel times from seconds to minutes (i.e., 59.9 min → 59 min) to have the travel time rasters s integer raster. This had to be changed to a *ceiling* function from version 5.8 onward. The default behaviour is now 59.9 min → 60 min. If this floor rounding option is checked, the behaviour gets back to the historical use of the *floor* function.                                                                                                         |
| Geographic coverage\ |                   |                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Referral\            |                   |                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Scaling up           |                   |                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+----------------------+-------------------+--------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Accessibility        | Analysis settings | Compute a cost allocation layer                                          | This option computes the cost allocation raster layer, a raster that contains the unique id of the nearest health facility by time (stored in the VALUE field). This unique id corresponds to the information stored in the 'cat' column of the health facility layer exportable from the 'Data' module. [The class for this raster is named "cost allocation".]{.c-blue}                                                                                                                                                    |
+----------------------+-------------------+--------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

The internal data sets are the following

1.  [Friction raster of class “friction”:]{.underline} Raster format layer containing the spatial distribution of the frictions (i.e. the resistance that one encounter when moving across the cells in a raster format layer). This is expressed in number of seconds to travel through a cell.
2.  [Speed raster of class "speed":]{.underline} Raster format layer containing the spatial distribution of the speeds used in the analysis. The values in the raster correspond to a composite suite of numbers. The first number is the code for the travelling mode (1: walking; 2: bicycling; 3: motorized). The six following numbers is the speed in km/h, with the first 3 numbers for the integer part, and the three following ones for the decimal part. As an example, the number "2012500" corresponds to bicycle with a speed of 12.5 km/h.
