---
title: "AccessMod 5 user manual"
other-links:
  - text: "Version française"
    href: ../fr/index.qmd
    icon: translate
---

Welcome to AccessMod 5 user manual!

If you are looking at the printed/pdf version of this manual, make sure to also check the online version of AccessMod 5 manual, which is always the most up-to-date version, in English ([https://accessmod.atlassian.net/wiki/spaces/EN](index.qmd)) or French ([https://accessmod.atlassian.net/wiki/spaces/FRAN](../fr/index.qmd)).

The main AccessMod website is found here: [https://accessmod.org](https://accessmod.org/)

**Main authors of the manual:** [Prof. Nicolas Ray](https://www.unige.ch/medecine/isg/en/research/1000ray/), [Dr. Steeve Ebener](https://www.linkedin.com/in/steeveebener/), Mr. Frederic Moser

**How to cite this manual:\
**Ray, N., Ebener, S., Moser, F. 2022. AccessMod 5 user manual, version 5.x, online version. [https://accessmod.atlassian.net/wiki/spaces/EN](index.qmd) 

**Please see the AccessMod GitHub page for a full list of all changes and bug fixes: <https://github.com/unige-geohealth/accessmod/blob/devel/changes.md>**

**Document version control**

+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Manual Version** | **Date of**\ | **Name of editor(s)**       | **AccessMod version** | **Changes**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                    | **version**  |                             |                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5.8                | 26.12.2022   | N. Ray, C. Ochoa            | 5.8                   | AccessMod now runs under Docker, either through 1) the Virtual machine (as before), 2) a dedicated launcher application, or 3) directly through Docker installed on the user machine. Possibility to go back to previous versions. Possibility to use the "Knight's move" for the cost-distance analysis. Possibility to generate a cost-allocation raster in the accessibility analysis. Zonal statistics can be done for several travel time at once. Faster analyses and better responsiveness. A command-line version of accessMod ("Replay" mode) is available. Updates of most librairies in the stack, many improvements under the hood and bug corrections. |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5.6.25             | 28.11.2019   | N. Ray                      | 5.6.25                | Faster computation of large countries at high resolution; import and export of full projects (settings and data); geographic coverage analysis is now possible without consideration of maximum capacity; automatic adjustment of population census in "correct for population" module; more precision in output of the referral module.                                                                                                                                                                                                                                                                                                                            |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5.6.11.2           | 1.9.2019     | N. Ray                      | 5.6.11.2              | New class raster "imported travel time" to import travel time raster produced elsewhere. Conversion in integer format of the imported "land cover" raster. Improved visibility of new available version of the software.                                                                                                                                                                                                                                                                                                                                                                                                                                            |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5.6.4              | 10.6.2019    | N. Ray                      | 5.6.4                 | Updated new links to online manuals. Updated the "stack item" description in 5.5.2 to account for change in behaviour. Updated 5.5.6 for the description of max. travel time.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5.6.0              | 1.5.2019     | N. Ray, Y. Guigoz           | 5.6.0                 | Updated several parts of the user guide to account for the major version 5.6 release                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5.3.2.1            | 8.4.2019     | N. Ray                      | 5.3.2                 | Updated various parts of the user guide with the suggested improvements listed in issue [#155](https://github.com/fxi/AccessMod_shiny/issues/155) on Github                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5.3.2              | 11.3.2019    | N. Ray                      | 5.3.2                 | Updated various parts of the user guide, and all screenshots, to reflect the new functionalities                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5.2.1              | 29.9.2018    | N. Ray, S. Ebener           | 5.2.1                 | Updated several parts of the user guide to reflect the new functionalities in version 5.2.1 and improve some parts of the text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5.2.1              | 29.9.2018    | N. Ray, S. Ebener           | 5.2.1                 | Updated several parts of the user guide to reflect the new functionalities in version 5.2.1 and improve some parts of the text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5.1.12             | 11.05.2018   | N. Ray                      | 5.1.12                | Edited version with description of the new facility selector/filter tool. Add details about AccessMod update under section 5.1. New numbering scheme for the document (it now matches the AccessMod version on which it is based)                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1.1.0              | 01.07.2017   | N. Ray, S. Ebener           | 5.0.7                 | Edited version taken into accounts comments/edits from: Michelle Schmitz, Karin Stenberg, Andrew Curtis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1.0.0              | 24.06.2017   | N. Ray, S. Ebener, F. Moser | 5.0.7                 | Initial complete document                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
+--------------------+--------------+-----------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## In this section

- [Acknowledgements](acknowledgements.qmd)
- [1. Introduction](1-introduction.qmd)
- [2. Tool updates compared to version 4.0](2-tool-updates-compared-to-version-4-0.qmd)
- [3. Using AccessMod 5](3-using-accessmod-5.qmd)
- [4. Installation of AccessMod 5](4-installation-of-accessmod-5.qmd)
- [5. AccessMod Tutorial](5-accessmod-tutorial.qmd)
- [6. References](6-references.qmd)
- [Appendix 1 - Automatic workflow for the correction of population on barriers](appendix-1-automatic-workflow-for-the-correction-of-population-on-barr.qmd)
- [Appendix 2 - Maximum population coverage capacity of health facilities](appendix-2-maximum-population-coverage-capacity-of-health-facilities.qmd)
- [Appendix 3 - Calculation details - Accessibility analysis](appendix-3-calculation-details-accessibility-analysis.qmd)
- [Appendix 4 - Calculation details - Geographic coverage analysis](appendix-4-calculation-details-geographic-coverage-analysis.qmd)
- [Appendix 5 - Calculation details - Referral analysis](appendix-5-calculation-details-referral-analysis.qmd)
- [Appendix 6 - Calculation details - Zonal statistics](appendix-6-calculation-details-zonal-statistics.qmd)
- [Appendix 7 - Calculation details - Scaling up analysis](appendix-7-calculation-details-scaling-up-analysis.qmd)
- [Appendix 8 - Replay functionality](appendix-8-replay-functionality.qmd)
- [Appendix 9 - Installation and use of AccessMod via Docker desktop](appendix-9-installation-and-use-of-accessmod-via-docker-desktop.qmd)
