---
title: "4.1. Aperçu de l'installation"
other-links:
  - text: "English version"
    href: ../en/4-1-installation-overview.qmd
    icon: translate
---

**AccessMod 5** est emballé dans une image, un paquet logiciel léger, autonome et exécutable qui contient tout ce qui est nécessaire pour exécuter une application. Cette image est basée sur Docker, une plateforme ouverte pour le développement, l'expédition et l'exécution d'applications, et peut être déployée soit par le biais d'une machine virtuelle à l'aide de **VirtualBox**, soit directement par le biais du **Docker desktop**. La machine virtuelle est un système d'exploitation encapsulé qui fonctionne dans de nombreux systèmes d'exploitation faisant office d'hôtes. Cependant, la virtualisation nécessite certaines ressources informatiques, ce qui rend généralement AccessMod plus efficace lorsque l'image est utilisée directement dans **Docker desktop**. Néanmoins, l'installation recommandée par défaut (mise en évidence ci-dessous) est la combinaison d'une machine virtuelle (fichiers `.ova`) et de VirtualBox comme gestionnaire de machine virtuelle. La description de l'installation d'AccessMod via VirtualBox est décrite dans la [section suivante](4-2-processus-d-installation-via-virtualbox.qmd). D'autres descriptions pour installer et utiliser AccessMod via Docker sont décrites dans les [annexes](annexe-9-installation-et-utilisation-d-accessmod-via-docker-desktop.qmd).

Le tableau suivant donne un aperçu des plates-formes permettant d'utiliser AccessMod, des infrastructures informatiques avec lesquelles elles fonctionnent et du type général d'utilisateur qui pourrait être intéressé par leur utilisation.

+---------------+--------------------------------------------+----------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| Utilisateur   | Utilisation                                | AccessMod plateforme             | Infrastructure informatique                                          | Tutoriel                                                                                                                                 |
+---------------+--------------------------------------------+----------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| Standard      | Sporadique et/ou des modèles simples       | VirtualBox\                      | **`.ova`** pour toute infrastructure\                                | [Processus d'installation via VirtualBox](4-2-processus-d-installation-via-virtualbox.qmd)                                               |
|               |                                            | \                                | Spécifique pour le fichier d'installation de VirtualBox              |                                                                                                                                          |
+---------------+--------------------------------------------+----------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| Intermédiaire | Fréquent et/ou des modèles complexes       | Docker via le lanceur "électron" | Fichiers **`.exe`** et **`.dmg`** pour les PC Intel Windows et Apple | [Installation d'AccessMod via le lanceur "électron"](9-2-installation-d-accessmod-via-le-lanceur-electron.qmd)\                          |
|               |                                            |                                  |                                                                      | \                                                                                                                                        |
|               |                                            |                                  | (Actuellement) **`.dmg`** + **mise à jour** pour les PC Apple M1     | [Installation de Docker desktop](9-1-installation-de-docker-desktop.qmd)                                                                 |
|               |                                            |                                  |                                                                      |                                                                                                                                          |
|               |                                            |                                  | Installateur pour Docker spécifique à chaque infrastructure          |                                                                                                                                          |
+---------------+--------------------------------------------+----------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| Avancé        |  Constant et/ou des modèles très complexes | Docker via la ligne de commande  | Pour toute infrastructure\                                           | [Installation d'AccessMod via Docker compose (ligne de commande)](9-3-installation-d-accessmod-via-docker-compose-ligne-de-commande.qmd) |
|               |                                            |                                  | Extraction directe du référentiel                                    |                                                                                                                                          |
+---------------+--------------------------------------------+----------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+
